// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: service/dex-finance/coin.proto

package dex_finance

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Coin_GetCoin_FullMethodName = "/api.service.dex_finance.Coin/GetCoin"
)

// CoinClient is the client API for Coin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoinClient interface {
	GetCoin(ctx context.Context, in *GetCoinRequest, opts ...grpc.CallOption) (*GetCoinReply, error)
}

type coinClient struct {
	cc grpc.ClientConnInterface
}

func NewCoinClient(cc grpc.ClientConnInterface) CoinClient {
	return &coinClient{cc}
}

func (c *coinClient) GetCoin(ctx context.Context, in *GetCoinRequest, opts ...grpc.CallOption) (*GetCoinReply, error) {
	out := new(GetCoinReply)
	err := c.cc.Invoke(ctx, Coin_GetCoin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoinServer is the server API for Coin service.
// All implementations must embed UnimplementedCoinServer
// for forward compatibility
type CoinServer interface {
	GetCoin(context.Context, *GetCoinRequest) (*GetCoinReply, error)
	mustEmbedUnimplementedCoinServer()
}

// UnimplementedCoinServer must be embedded to have forward compatible implementations.
type UnimplementedCoinServer struct {
}

func (UnimplementedCoinServer) GetCoin(context.Context, *GetCoinRequest) (*GetCoinReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoin not implemented")
}
func (UnimplementedCoinServer) mustEmbedUnimplementedCoinServer() {}

// UnsafeCoinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoinServer will
// result in compilation errors.
type UnsafeCoinServer interface {
	mustEmbedUnimplementedCoinServer()
}

func RegisterCoinServer(s grpc.ServiceRegistrar, srv CoinServer) {
	s.RegisterService(&Coin_ServiceDesc, srv)
}

func _Coin_GetCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).GetCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coin_GetCoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).GetCoin(ctx, req.(*GetCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Coin_ServiceDesc is the grpc.ServiceDesc for Coin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.service.dex_finance.Coin",
	HandlerType: (*CoinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCoin",
			Handler:    _Coin_GetCoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/dex-finance/coin.proto",
}
