// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: interface/dex/assets.proto

package dex

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Assets_GetUserAccountsAssets_FullMethodName = "/api.interface.dex.Assets/GetUserAccountsAssets"
)

// AssetsClient is the client API for Assets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetsClient interface {
	GetUserAccountsAssets(ctx context.Context, in *GetUserAccountsAssetsRequest, opts ...grpc.CallOption) (*GetUserAccountsAssetsReply, error)
}

type assetsClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetsClient(cc grpc.ClientConnInterface) AssetsClient {
	return &assetsClient{cc}
}

func (c *assetsClient) GetUserAccountsAssets(ctx context.Context, in *GetUserAccountsAssetsRequest, opts ...grpc.CallOption) (*GetUserAccountsAssetsReply, error) {
	out := new(GetUserAccountsAssetsReply)
	err := c.cc.Invoke(ctx, Assets_GetUserAccountsAssets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetsServer is the server API for Assets service.
// All implementations must embed UnimplementedAssetsServer
// for forward compatibility
type AssetsServer interface {
	GetUserAccountsAssets(context.Context, *GetUserAccountsAssetsRequest) (*GetUserAccountsAssetsReply, error)
	mustEmbedUnimplementedAssetsServer()
}

// UnimplementedAssetsServer must be embedded to have forward compatible implementations.
type UnimplementedAssetsServer struct {
}

func (UnimplementedAssetsServer) GetUserAccountsAssets(context.Context, *GetUserAccountsAssetsRequest) (*GetUserAccountsAssetsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAccountsAssets not implemented")
}
func (UnimplementedAssetsServer) mustEmbedUnimplementedAssetsServer() {}

// UnsafeAssetsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetsServer will
// result in compilation errors.
type UnsafeAssetsServer interface {
	mustEmbedUnimplementedAssetsServer()
}

func RegisterAssetsServer(s grpc.ServiceRegistrar, srv AssetsServer) {
	s.RegisterService(&Assets_ServiceDesc, srv)
}

func _Assets_GetUserAccountsAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAccountsAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServer).GetUserAccountsAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Assets_GetUserAccountsAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServer).GetUserAccountsAssets(ctx, req.(*GetUserAccountsAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Assets_ServiceDesc is the grpc.ServiceDesc for Assets service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Assets_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.interface.dex.Assets",
	HandlerType: (*AssetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserAccountsAssets",
			Handler:    _Assets_GetUserAccountsAssets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interface/dex/assets.proto",
}
