{
 "title": "Web3 Template",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Chain Gas Price",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    info.unique_id,\n    info.chain_id,\n    info.logo_url,\n    info.chain_name,\n    info.chain_env,\n    metrics.latest_block_number,\n    metrics.gas_price / 1e9 AS gas_price,\n    metrics.tx_tps AS tx_tps,\n    metrics.tx_tpd AS tx_tpd,\n    metrics.tx_pending AS tx_pending,\n    metrics.token_price_usd AS token_price_usd,\n    info.explorer_url\nFROM web3.chain_metrics AS metrics\nLEFT JOIN web3.chain_info AS info ON  metrics.chain_unique_id = info.unique_id\nORDER BY info.order_seq DESC\n;"
    }
   ]
  },
  {
   "title": "Chain Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Gwei" } },
   "targets": [
    { "expr": "web3_chain_gas_price / 1e9", "legendFormat": "{{chain_name}} : {{chain_env}}" }
   ]
  },
  {
   "title": "Chain Transaction Deal",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "tx" } },
   "targets": [
    { "expr": "web3_chain_transaction_tps", "legendFormat": "{{chain_name}} : {{chain_env}}" }
   ]
  },
  {
   "title": "Chain Transaction Pending",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "tx" } },
   "targets": [
    { "expr": "web3_chain_transaction_pending", "legendFormat": "{{chain_name}} : {{chain_env}}" }
   ]
  },
  {
   "title": "MySQL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "tx" } },
   "targets": [
    {
     "expr": "sum by(cmd, table) (rate(mysql_requests_cmd_total[$__rate_interval]))",
     "legendFormat": "{{cmd}} {{table}}"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "tx" } },
   "targets": [
    {
     "expr": "sum by(cmd) (rate(redis_requests_cmd_total[$__rate_interval]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Client Send Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "tx" } },
   "targets": [
    {
     "expr": "sum by(kind, operation) (rate(client_request_total[$__rate_interval]))",
     "legendFormat": "{{kind}} {{operation}}"
    }
   ]
  },
  {
   "title": "Client Send Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "tx" } },
   "targets": [
    {
     "expr": "sum by(kind, operation) (rate(client_request_total[$__rate_interval]))",
     "legendFormat": "{{kind}} {{operation}}"
    }
   ]
  },
  {
   "title": "Abi Call Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "tx" } },
   "targets": [
    {
     "expr": "sum by(abi_method, chain_name) (rate(web3_abi_call_total[$__rate_interval]))",
     "legendFormat": "{{chain_name}} : {{abi_method}}"
    }
   ]
  },
  {
   "title": "Abi Call Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "tx" } },
   "targets": [
    {
     "expr": "sum by(abi_method, chain_name) (rate(web3_abi_call_total[$__rate_interval]))",
     "legendFormat": "{{chain_name}} : {{abi_method}}"
    }
   ]
  },
  {
   "title": "Abi Call by Chain",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(chain_name) (rate(web3_abi_call_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Abi Call by Provider",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(provider) (rate(web3_abi_call_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Abi Call by abi_method",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(abi_method) (rate(web3_abi_call_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}