// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChainMetric = "chain_metrics"

// ChainMetric mapped from table <chain_metrics>
type ChainMetric struct {
	ChainUniqueID     int64      `gorm:"column:chain_unique_id;type:bigint;primaryKey" json:"chain_unique_id"`
	LatestBlockNumber int64      `gorm:"column:latest_block_number;type:bigint;not null" json:"latest_block_number"`
	GasPrice          int64      `gorm:"column:gas_price;type:bigint;not null" json:"gas_price"`
	TxTps             float64    `gorm:"column:tx_tps;type:double;not null" json:"tx_tps"`
	TxTpd             float64    `gorm:"column:tx_tpd;type:double;not null" json:"tx_tpd"`
	CreatedAt         *time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:Create Time" json:"created_at"`
	UpdatedAt         *time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:Update Time" json:"updated_at"`
}

// TableName ChainMetric's table name
func (*ChainMetric) TableName() string {
	return TableNameChainMetric
}
