// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBlockTransaction = "block_transaction"

// BlockTransaction mapped from table <block_transaction>
type BlockTransaction struct {
	Type                 int64      `gorm:"column:type;type:bigint;not null" json:"type"`
	Status               int64      `gorm:"column:status;type:bigint;not null" json:"status"`
	BlockHash            string     `gorm:"column:block_hash;type:varchar(200)" json:"block_hash"`
	BlockNumber          int64      `gorm:"column:block_number;type:bigint;not null;comment:block number" json:"block_number"`
	BlockTimestamp       *time.Time `gorm:"column:block_timestamp;type:datetime;not null;index:transaction_block_timestamp_index,priority:1;default:CURRENT_TIMESTAMP;comment:Block Time" json:"block_timestamp"`
	TransactionHash      string     `gorm:"column:transaction_hash;type:varchar(200);primaryKey" json:"transaction_hash"`
	TransactionIndex     int64      `gorm:"column:transaction_index;type:bigint;not null" json:"transaction_index"`
	FromAddress          string     `gorm:"column:from_address;type:varchar(200)" json:"from_address"`
	ToAddress            string     `gorm:"column:to_address;type:varchar(200)" json:"to_address"`
	Input                string     `gorm:"column:input;type:text" json:"input"`
	Value                string     `gorm:"column:value;type:varchar(500)" json:"value"`
	Nonce                int64      `gorm:"column:nonce;type:bigint;not null" json:"nonce"`
	ContractAddress      string     `gorm:"column:contract_address;type:varchar(200)" json:"contract_address"`
	Gas                  int64      `gorm:"column:gas;type:bigint;not null" json:"gas"`
	GasPrice             int64      `gorm:"column:gas_price;type:bigint;not null" json:"gas_price"`
	GasUsed              int64      `gorm:"column:gas_used;type:bigint;not null" json:"gas_used"`
	EffectiveGasPrice    int64      `gorm:"column:effective_gas_price;type:bigint;not null" json:"effective_gas_price"`
	CumulativeGasUsed    int64      `gorm:"column:cumulative_gas_used;type:bigint;not null" json:"cumulative_gas_used"`
	MaxFeePerGas         int64      `gorm:"column:max_fee_per_gas;type:bigint;not null" json:"max_fee_per_gas"`
	MaxPriorityFeePerGas int64      `gorm:"column:max_priority_fee_per_gas;type:bigint;not null" json:"max_priority_fee_per_gas"`
	R                    string     `gorm:"column:r;type:varchar(200)" json:"r"`
	S                    string     `gorm:"column:s;type:varchar(200)" json:"s"`
	V                    int64      `gorm:"column:v;type:bigint;not null" json:"v"`
	LogsCount            int64      `gorm:"column:logs_count;type:bigint;not null" json:"logs_count"`
	ChainID              int64      `gorm:"column:chain_id;type:bigint;not null" json:"chain_id"`
	ChainUniqueID        int64      `gorm:"column:chain_unique_id;type:bigint" json:"chain_unique_id"`
	CreatedAt            *time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:Create Time" json:"created_at"`
	UpdatedAt            *time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:Update Time" json:"updated_at"`
}

// TableName BlockTransaction's table name
func (*BlockTransaction) TableName() string {
	return TableNameBlockTransaction
}
