// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChainClient = "chain_client"

// ChainClient mapped from table <chain_client>
type ChainClient struct {
	ID              int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ChainUniqueID   int64      `gorm:"column:chain_unique_id;type:bigint;not null" json:"chain_unique_id"`
	ChainID         int64      `gorm:"column:chain_id;type:bigint;not null" json:"chain_id"`
	ProviderName    *string    `gorm:"column:provider_name;type:varchar(200);not null;default:0" json:"provider_name"`
	ProviderID      int64      `gorm:"column:provider_id;type:bigint;not null" json:"provider_id"`
	TransportSchema string     `gorm:"column:transport_schema;type:varchar(100);not null" json:"transport_schema"`
	TransportURL    string     `gorm:"column:transport_url;type:varchar(500)" json:"transport_url"`
	Priority        int64      `gorm:"column:priority;type:bigint;not null" json:"priority"`
	CreatedAt       *time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:Create Time" json:"created_at"`
	UpdatedAt       *time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:Update Time" json:"updated_at"`
}

// TableName ChainClient's table name
func (*ChainClient) TableName() string {
	return TableNameChainClient
}
