// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChainInfo = "chain_info"

// ChainInfo mapped from table <chain_info>
type ChainInfo struct {
	UniqueID    int64      `gorm:"column:unique_id;type:bigint;primaryKey" json:"unique_id"`
	TokenSymbol string     `gorm:"column:token_symbol;type:varchar(100);not null" json:"token_symbol"`
	OrderSeq    int64      `gorm:"column:order_seq;type:bigint;not null" json:"order_seq"`
	ChainID     int64      `gorm:"column:chain_id;type:bigint;not null" json:"chain_id"`
	ChainName   string     `gorm:"column:chain_name;type:varchar(100);not null" json:"chain_name"`
	ChainEnv    string     `gorm:"column:chain_env;type:varchar(50);not null" json:"chain_env"`
	LogoURL     string     `gorm:"column:logo_url;type:varchar(100);not null" json:"logo_url"`
	WebsiteURL  string     `gorm:"column:website_url;type:varchar(200);not null" json:"website_url"`
	ExplorerURL string     `gorm:"column:explorer_url;type:varchar(200);not null" json:"explorer_url"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:datetime;default:now()" json:"updated_at"`
}

// TableName ChainInfo's table name
func (*ChainInfo) TableName() string {
	return TableNameChainInfo
}
