// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: interface/web3/defi.proto

package web3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetTokenPriceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTokenPriceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTokenPriceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTokenPriceRequestMultiError, or nil if none found.
func (m *GetTokenPriceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTokenPriceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SourceToken

	// no validation rules for TargetToken

	if len(errors) > 0 {
		return GetTokenPriceRequestMultiError(errors)
	}

	return nil
}

// GetTokenPriceRequestMultiError is an error wrapping multiple validation
// errors returned by GetTokenPriceRequest.ValidateAll() if the designated
// constraints aren't met.
type GetTokenPriceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTokenPriceRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTokenPriceRequestMultiError) AllErrors() []error { return m }

// GetTokenPriceRequestValidationError is the validation error returned by
// GetTokenPriceRequest.Validate if the designated constraints aren't met.
type GetTokenPriceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTokenPriceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTokenPriceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTokenPriceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTokenPriceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTokenPriceRequestValidationError) ErrorName() string {
	return "GetTokenPriceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTokenPriceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTokenPriceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTokenPriceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTokenPriceRequestValidationError{}

// Validate checks the field values on GetTokenPriceReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTokenPriceReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTokenPriceReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTokenPriceReplyMultiError, or nil if none found.
func (m *GetTokenPriceReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTokenPriceReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetPrice()))
		i := 0
		for key := range m.GetPrice() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetPrice()[key]
			_ = val

			// no validation rules for Price[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, GetTokenPriceReplyValidationError{
							field:  fmt.Sprintf("Price[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, GetTokenPriceReplyValidationError{
							field:  fmt.Sprintf("Price[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return GetTokenPriceReplyValidationError{
						field:  fmt.Sprintf("Price[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if len(errors) > 0 {
		return GetTokenPriceReplyMultiError(errors)
	}

	return nil
}

// GetTokenPriceReplyMultiError is an error wrapping multiple validation errors
// returned by GetTokenPriceReply.ValidateAll() if the designated constraints
// aren't met.
type GetTokenPriceReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTokenPriceReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTokenPriceReplyMultiError) AllErrors() []error { return m }

// GetTokenPriceReplyValidationError is the validation error returned by
// GetTokenPriceReply.Validate if the designated constraints aren't met.
type GetTokenPriceReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTokenPriceReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTokenPriceReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTokenPriceReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTokenPriceReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTokenPriceReplyValidationError) ErrorName() string {
	return "GetTokenPriceReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetTokenPriceReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTokenPriceReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTokenPriceReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTokenPriceReplyValidationError{}

// Validate checks the field values on GetTokenPriceReply_Price with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTokenPriceReply_Price) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTokenPriceReply_Price with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTokenPriceReply_PriceMultiError, or nil if none found.
func (m *GetTokenPriceReply_Price) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTokenPriceReply_Price) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Price

	// no validation rules for Timestamp

	// no validation rules for SourceToken

	// no validation rules for TargetToken

	if len(errors) > 0 {
		return GetTokenPriceReply_PriceMultiError(errors)
	}

	return nil
}

// GetTokenPriceReply_PriceMultiError is an error wrapping multiple validation
// errors returned by GetTokenPriceReply_Price.ValidateAll() if the designated
// constraints aren't met.
type GetTokenPriceReply_PriceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTokenPriceReply_PriceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTokenPriceReply_PriceMultiError) AllErrors() []error { return m }

// GetTokenPriceReply_PriceValidationError is the validation error returned by
// GetTokenPriceReply_Price.Validate if the designated constraints aren't met.
type GetTokenPriceReply_PriceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTokenPriceReply_PriceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTokenPriceReply_PriceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTokenPriceReply_PriceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTokenPriceReply_PriceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTokenPriceReply_PriceValidationError) ErrorName() string {
	return "GetTokenPriceReply_PriceValidationError"
}

// Error satisfies the builtin error interface
func (e GetTokenPriceReply_PriceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTokenPriceReply_Price.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTokenPriceReply_PriceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTokenPriceReply_PriceValidationError{}
