// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: service/data/chain.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncBlockInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *BlockItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *SyncBlockInfoRequest) Reset() {
	*x = SyncBlockInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_data_chain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBlockInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBlockInfoRequest) ProtoMessage() {}

func (x *SyncBlockInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_data_chain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBlockInfoRequest.ProtoReflect.Descriptor instead.
func (*SyncBlockInfoRequest) Descriptor() ([]byte, []int) {
	return file_service_data_chain_proto_rawDescGZIP(), []int{0}
}

func (x *SyncBlockInfoRequest) GetItem() *BlockItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type SyncBlockInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncBlockInfoReply) Reset() {
	*x = SyncBlockInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_data_chain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBlockInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBlockInfoReply) ProtoMessage() {}

func (x *SyncBlockInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_data_chain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBlockInfoReply.ProtoReflect.Descriptor instead.
func (*SyncBlockInfoReply) Descriptor() ([]byte, []int) {
	return file_service_data_chain_proto_rawDescGZIP(), []int{1}
}

type SyncBlockTransactionInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *TransactionItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *SyncBlockTransactionInfoRequest) Reset() {
	*x = SyncBlockTransactionInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_data_chain_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBlockTransactionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBlockTransactionInfoRequest) ProtoMessage() {}

func (x *SyncBlockTransactionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_data_chain_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBlockTransactionInfoRequest.ProtoReflect.Descriptor instead.
func (*SyncBlockTransactionInfoRequest) Descriptor() ([]byte, []int) {
	return file_service_data_chain_proto_rawDescGZIP(), []int{2}
}

func (x *SyncBlockTransactionInfoRequest) GetItem() *TransactionItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type SyncBlockTransactionInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncBlockTransactionInfoReply) Reset() {
	*x = SyncBlockTransactionInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_data_chain_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBlockTransactionInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBlockTransactionInfoReply) ProtoMessage() {}

func (x *SyncBlockTransactionInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_data_chain_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBlockTransactionInfoReply.ProtoReflect.Descriptor instead.
func (*SyncBlockTransactionInfoReply) Descriptor() ([]byte, []int) {
	return file_service_data_chain_proto_rawDescGZIP(), []int{3}
}

var File_service_data_chain_proto protoreflect.FileDescriptor

var file_service_data_chain_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x17, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x14, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a,
	0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x14,
	0x0a, 0x12, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x58, 0x0a, 0x1f, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x1f,
	0x0a, 0x1d, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32,
	0xe6, 0x01, 0x0a, 0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x5d, 0x0a, 0x0d, 0x53, 0x79, 0x6e,
	0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x79,
	0x6e, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x7e, 0x0a, 0x18, 0x53, 0x79, 0x6e, 0x63,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x30, 0x0a, 0x10, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x50, 0x01, 0x5a, 0x1a,
	0x77, 0x65, 0x62, 0x33, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x64, 0x61, 0x74, 0x61, 0x3b, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_service_data_chain_proto_rawDescOnce sync.Once
	file_service_data_chain_proto_rawDescData = file_service_data_chain_proto_rawDesc
)

func file_service_data_chain_proto_rawDescGZIP() []byte {
	file_service_data_chain_proto_rawDescOnce.Do(func() {
		file_service_data_chain_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_data_chain_proto_rawDescData)
	})
	return file_service_data_chain_proto_rawDescData
}

var file_service_data_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_data_chain_proto_goTypes = []interface{}{
	(*SyncBlockInfoRequest)(nil),            // 0: api.service.data.SyncBlockInfoRequest
	(*SyncBlockInfoReply)(nil),              // 1: api.service.data.SyncBlockInfoReply
	(*SyncBlockTransactionInfoRequest)(nil), // 2: api.service.data.SyncBlockTransactionInfoRequest
	(*SyncBlockTransactionInfoReply)(nil),   // 3: api.service.data.SyncBlockTransactionInfoReply
	(*BlockItem)(nil),                       // 4: api.service.data.BlockItem
	(*TransactionItem)(nil),                 // 5: api.service.data.TransactionItem
}
var file_service_data_chain_proto_depIdxs = []int32{
	4, // 0: api.service.data.SyncBlockInfoRequest.item:type_name -> api.service.data.BlockItem
	5, // 1: api.service.data.SyncBlockTransactionInfoRequest.item:type_name -> api.service.data.TransactionItem
	0, // 2: api.service.data.Chain.SyncBlockInfo:input_type -> api.service.data.SyncBlockInfoRequest
	2, // 3: api.service.data.Chain.SyncBlockTransactionInfo:input_type -> api.service.data.SyncBlockTransactionInfoRequest
	1, // 4: api.service.data.Chain.SyncBlockInfo:output_type -> api.service.data.SyncBlockInfoReply
	3, // 5: api.service.data.Chain.SyncBlockTransactionInfo:output_type -> api.service.data.SyncBlockTransactionInfoReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_data_chain_proto_init() }
func file_service_data_chain_proto_init() {
	if File_service_data_chain_proto != nil {
		return
	}
	file_service_data_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_data_chain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBlockInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_data_chain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBlockInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_data_chain_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBlockTransactionInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_data_chain_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBlockTransactionInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_data_chain_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_data_chain_proto_goTypes,
		DependencyIndexes: file_service_data_chain_proto_depIdxs,
		MessageInfos:      file_service_data_chain_proto_msgTypes,
	}.Build()
	File_service_data_chain_proto = out.File
	file_service_data_chain_proto_rawDesc = nil
	file_service_data_chain_proto_goTypes = nil
	file_service_data_chain_proto_depIdxs = nil
}
