// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: service/data/chain.proto

package data

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SyncBlockInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SyncBlockInfoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SyncBlockInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SyncBlockInfoRequestMultiError, or nil if none found.
func (m *SyncBlockInfoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SyncBlockInfoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SyncBlockInfoRequestValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SyncBlockInfoRequestValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SyncBlockInfoRequestValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SyncBlockInfoRequestMultiError(errors)
	}

	return nil
}

// SyncBlockInfoRequestMultiError is an error wrapping multiple validation
// errors returned by SyncBlockInfoRequest.ValidateAll() if the designated
// constraints aren't met.
type SyncBlockInfoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SyncBlockInfoRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SyncBlockInfoRequestMultiError) AllErrors() []error { return m }

// SyncBlockInfoRequestValidationError is the validation error returned by
// SyncBlockInfoRequest.Validate if the designated constraints aren't met.
type SyncBlockInfoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SyncBlockInfoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SyncBlockInfoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SyncBlockInfoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SyncBlockInfoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SyncBlockInfoRequestValidationError) ErrorName() string {
	return "SyncBlockInfoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SyncBlockInfoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSyncBlockInfoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SyncBlockInfoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SyncBlockInfoRequestValidationError{}

// Validate checks the field values on SyncBlockInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SyncBlockInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SyncBlockInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SyncBlockInfoReplyMultiError, or nil if none found.
func (m *SyncBlockInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SyncBlockInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SyncBlockInfoReplyMultiError(errors)
	}

	return nil
}

// SyncBlockInfoReplyMultiError is an error wrapping multiple validation errors
// returned by SyncBlockInfoReply.ValidateAll() if the designated constraints
// aren't met.
type SyncBlockInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SyncBlockInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SyncBlockInfoReplyMultiError) AllErrors() []error { return m }

// SyncBlockInfoReplyValidationError is the validation error returned by
// SyncBlockInfoReply.Validate if the designated constraints aren't met.
type SyncBlockInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SyncBlockInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SyncBlockInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SyncBlockInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SyncBlockInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SyncBlockInfoReplyValidationError) ErrorName() string {
	return "SyncBlockInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SyncBlockInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSyncBlockInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SyncBlockInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SyncBlockInfoReplyValidationError{}

// Validate checks the field values on SyncBlockTransactionInfoRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SyncBlockTransactionInfoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SyncBlockTransactionInfoRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// SyncBlockTransactionInfoRequestMultiError, or nil if none found.
func (m *SyncBlockTransactionInfoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SyncBlockTransactionInfoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SyncBlockTransactionInfoRequestValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SyncBlockTransactionInfoRequestValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SyncBlockTransactionInfoRequestValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SyncBlockTransactionInfoRequestMultiError(errors)
	}

	return nil
}

// SyncBlockTransactionInfoRequestMultiError is an error wrapping multiple
// validation errors returned by SyncBlockTransactionInfoRequest.ValidateAll()
// if the designated constraints aren't met.
type SyncBlockTransactionInfoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SyncBlockTransactionInfoRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SyncBlockTransactionInfoRequestMultiError) AllErrors() []error { return m }

// SyncBlockTransactionInfoRequestValidationError is the validation error
// returned by SyncBlockTransactionInfoRequest.Validate if the designated
// constraints aren't met.
type SyncBlockTransactionInfoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SyncBlockTransactionInfoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SyncBlockTransactionInfoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SyncBlockTransactionInfoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SyncBlockTransactionInfoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SyncBlockTransactionInfoRequestValidationError) ErrorName() string {
	return "SyncBlockTransactionInfoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SyncBlockTransactionInfoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSyncBlockTransactionInfoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SyncBlockTransactionInfoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SyncBlockTransactionInfoRequestValidationError{}

// Validate checks the field values on SyncBlockTransactionInfoReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SyncBlockTransactionInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SyncBlockTransactionInfoReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// SyncBlockTransactionInfoReplyMultiError, or nil if none found.
func (m *SyncBlockTransactionInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SyncBlockTransactionInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SyncBlockTransactionInfoReplyMultiError(errors)
	}

	return nil
}

// SyncBlockTransactionInfoReplyMultiError is an error wrapping multiple
// validation errors returned by SyncBlockTransactionInfoReply.ValidateAll()
// if the designated constraints aren't met.
type SyncBlockTransactionInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SyncBlockTransactionInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SyncBlockTransactionInfoReplyMultiError) AllErrors() []error { return m }

// SyncBlockTransactionInfoReplyValidationError is the validation error
// returned by SyncBlockTransactionInfoReply.Validate if the designated
// constraints aren't met.
type SyncBlockTransactionInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SyncBlockTransactionInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SyncBlockTransactionInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SyncBlockTransactionInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SyncBlockTransactionInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SyncBlockTransactionInfoReplyValidationError) ErrorName() string {
	return "SyncBlockTransactionInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SyncBlockTransactionInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSyncBlockTransactionInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SyncBlockTransactionInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SyncBlockTransactionInfoReplyValidationError{}
