// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: service/data/defi.proto

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Defi_GetDefiPrice_FullMethodName = "/api.service.data.Defi/GetDefiPrice"
)

// DefiClient is the client API for Defi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DefiClient interface {
	GetDefiPrice(ctx context.Context, in *GetDefiPriceRequest, opts ...grpc.CallOption) (*GetDefiPriceReply, error)
}

type defiClient struct {
	cc grpc.ClientConnInterface
}

func NewDefiClient(cc grpc.ClientConnInterface) DefiClient {
	return &defiClient{cc}
}

func (c *defiClient) GetDefiPrice(ctx context.Context, in *GetDefiPriceRequest, opts ...grpc.CallOption) (*GetDefiPriceReply, error) {
	out := new(GetDefiPriceReply)
	err := c.cc.Invoke(ctx, Defi_GetDefiPrice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DefiServer is the server API for Defi service.
// All implementations must embed UnimplementedDefiServer
// for forward compatibility
type DefiServer interface {
	GetDefiPrice(context.Context, *GetDefiPriceRequest) (*GetDefiPriceReply, error)
	mustEmbedUnimplementedDefiServer()
}

// UnimplementedDefiServer must be embedded to have forward compatible implementations.
type UnimplementedDefiServer struct {
}

func (UnimplementedDefiServer) GetDefiPrice(context.Context, *GetDefiPriceRequest) (*GetDefiPriceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefiPrice not implemented")
}
func (UnimplementedDefiServer) mustEmbedUnimplementedDefiServer() {}

// UnsafeDefiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DefiServer will
// result in compilation errors.
type UnsafeDefiServer interface {
	mustEmbedUnimplementedDefiServer()
}

func RegisterDefiServer(s grpc.ServiceRegistrar, srv DefiServer) {
	s.RegisterService(&Defi_ServiceDesc, srv)
}

func _Defi_GetDefiPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefiPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefiServer).GetDefiPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Defi_GetDefiPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefiServer).GetDefiPrice(ctx, req.(*GetDefiPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Defi_ServiceDesc is the grpc.ServiceDesc for Defi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Defi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.service.data.Defi",
	HandlerType: (*DefiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDefiPrice",
			Handler:    _Defi_GetDefiPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/data/defi.proto",
}
