// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: service/dex-member/auth.proto

package dex_member

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthSignInRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AuthSignInRequest) Reset() {
	*x = AuthSignInRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_dex_member_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthSignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignInRequest) ProtoMessage() {}

func (x *AuthSignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_dex_member_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignInRequest.ProtoReflect.Descriptor instead.
func (*AuthSignInRequest) Descriptor() ([]byte, []int) {
	return file_service_dex_member_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthSignInRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthSignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthSignInReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JwtToken string `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
}

func (x *AuthSignInReply) Reset() {
	*x = AuthSignInReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_dex_member_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthSignInReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignInReply) ProtoMessage() {}

func (x *AuthSignInReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_dex_member_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignInReply.ProtoReflect.Descriptor instead.
func (*AuthSignInReply) Descriptor() ([]byte, []int) {
	return file_service_dex_member_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthSignInReply) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

type AuthSignUpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthSignUpRequest) Reset() {
	*x = AuthSignUpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_dex_member_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthSignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignUpRequest) ProtoMessage() {}

func (x *AuthSignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_dex_member_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignUpRequest.ProtoReflect.Descriptor instead.
func (*AuthSignUpRequest) Descriptor() ([]byte, []int) {
	return file_service_dex_member_auth_proto_rawDescGZIP(), []int{2}
}

type AuthSignUpReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthSignUpReply) Reset() {
	*x = AuthSignUpReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_dex_member_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthSignUpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignUpReply) ProtoMessage() {}

func (x *AuthSignUpReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_dex_member_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignUpReply.ProtoReflect.Descriptor instead.
func (*AuthSignUpReply) Descriptor() ([]byte, []int) {
	return file_service_dex_member_auth_proto_rawDescGZIP(), []int{3}
}

type AuthVerifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JwtToken string `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
}

func (x *AuthVerifyRequest) Reset() {
	*x = AuthVerifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_dex_member_auth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthVerifyRequest) ProtoMessage() {}

func (x *AuthVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_dex_member_auth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthVerifyRequest.ProtoReflect.Descriptor instead.
func (*AuthVerifyRequest) Descriptor() ([]byte, []int) {
	return file_service_dex_member_auth_proto_rawDescGZIP(), []int{4}
}

func (x *AuthVerifyRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

type AuthVerifyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *UserItem `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *AuthVerifyReply) Reset() {
	*x = AuthVerifyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_dex_member_auth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthVerifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthVerifyReply) ProtoMessage() {}

func (x *AuthVerifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_dex_member_auth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthVerifyReply.ProtoReflect.Descriptor instead.
func (*AuthVerifyReply) Descriptor() ([]byte, []int) {
	return file_service_dex_member_auth_proto_rawDescGZIP(), []int{5}
}

func (x *AuthVerifyReply) GetUser() *UserItem {
	if x != nil {
		return x.User
	}
	return nil
}

var File_service_dex_member_auth_proto protoreflect.FileDescriptor

var file_service_dex_member_auth_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x65, 0x78, 0x2d, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x16, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x78,
	0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x1d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x64, 0x65, 0x78, 0x2d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x68, 0x53, 0x69,
	0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2e, 0x0a,
	0x0f, 0x41, 0x75, 0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x77, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x13, 0x0a,
	0x11, 0x41, 0x75, 0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x75, 0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x30, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x68, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x77,
	0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a,
	0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x47, 0x0a, 0x0f, 0x41, 0x75, 0x74, 0x68, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x78, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x32, 0xac, 0x02, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x60, 0x0a, 0x0a, 0x41, 0x75, 0x74,
	0x68, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x12, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x78, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x64, 0x65, 0x78, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x60, 0x0a, 0x0a, 0x41,
	0x75, 0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x12, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x78, 0x5f, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x64, 0x65, 0x78, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x60, 0x0a,
	0x0a, 0x41, 0x75, 0x74, 0x68, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x29, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x78, 0x5f, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x78, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42,
	0x42, 0x0a, 0x16, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64,
	0x65, 0x78, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x26, 0x77, 0x65, 0x62,
	0x33, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x65,
	0x78, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x3b, 0x64, 0x65, 0x78, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_dex_member_auth_proto_rawDescOnce sync.Once
	file_service_dex_member_auth_proto_rawDescData = file_service_dex_member_auth_proto_rawDesc
)

func file_service_dex_member_auth_proto_rawDescGZIP() []byte {
	file_service_dex_member_auth_proto_rawDescOnce.Do(func() {
		file_service_dex_member_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_dex_member_auth_proto_rawDescData)
	})
	return file_service_dex_member_auth_proto_rawDescData
}

var file_service_dex_member_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_dex_member_auth_proto_goTypes = []interface{}{
	(*AuthSignInRequest)(nil), // 0: api.service.dex_member.AuthSignInRequest
	(*AuthSignInReply)(nil),   // 1: api.service.dex_member.AuthSignInReply
	(*AuthSignUpRequest)(nil), // 2: api.service.dex_member.AuthSignUpRequest
	(*AuthSignUpReply)(nil),   // 3: api.service.dex_member.AuthSignUpReply
	(*AuthVerifyRequest)(nil), // 4: api.service.dex_member.AuthVerifyRequest
	(*AuthVerifyReply)(nil),   // 5: api.service.dex_member.AuthVerifyReply
	(*UserItem)(nil),          // 6: api.service.dex_member.UserItem
}
var file_service_dex_member_auth_proto_depIdxs = []int32{
	6, // 0: api.service.dex_member.AuthVerifyReply.user:type_name -> api.service.dex_member.UserItem
	0, // 1: api.service.dex_member.Auth.AuthSignIn:input_type -> api.service.dex_member.AuthSignInRequest
	2, // 2: api.service.dex_member.Auth.AuthSignUp:input_type -> api.service.dex_member.AuthSignUpRequest
	4, // 3: api.service.dex_member.Auth.AuthVerify:input_type -> api.service.dex_member.AuthVerifyRequest
	1, // 4: api.service.dex_member.Auth.AuthSignIn:output_type -> api.service.dex_member.AuthSignInReply
	3, // 5: api.service.dex_member.Auth.AuthSignUp:output_type -> api.service.dex_member.AuthSignUpReply
	5, // 6: api.service.dex_member.Auth.AuthVerify:output_type -> api.service.dex_member.AuthVerifyReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_dex_member_auth_proto_init() }
func file_service_dex_member_auth_proto_init() {
	if File_service_dex_member_auth_proto != nil {
		return
	}
	file_service_dex_member_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_dex_member_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthSignInRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_dex_member_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthSignInReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_dex_member_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthSignUpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_dex_member_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthSignUpReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_dex_member_auth_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthVerifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_dex_member_auth_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthVerifyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_dex_member_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_dex_member_auth_proto_goTypes,
		DependencyIndexes: file_service_dex_member_auth_proto_depIdxs,
		MessageInfos:      file_service_dex_member_auth_proto_msgTypes,
	}.Build()
	File_service_dex_member_auth_proto = out.File
	file_service_dex_member_auth_proto_rawDesc = nil
	file_service_dex_member_auth_proto_goTypes = nil
	file_service_dex_member_auth_proto_depIdxs = nil
}
