// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: service/dex-member/auth.proto

package dex_member

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Auth_AuthSignIn_FullMethodName = "/api.service.dex_member.Auth/AuthSignIn"
	Auth_AuthSignUp_FullMethodName = "/api.service.dex_member.Auth/AuthSignUp"
	Auth_AuthVerify_FullMethodName = "/api.service.dex_member.Auth/AuthVerify"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	AuthSignIn(ctx context.Context, in *AuthSignInRequest, opts ...grpc.CallOption) (*AuthSignInReply, error)
	AuthSignUp(ctx context.Context, in *AuthSignUpRequest, opts ...grpc.CallOption) (*AuthSignUpReply, error)
	AuthVerify(ctx context.Context, in *AuthVerifyRequest, opts ...grpc.CallOption) (*AuthVerifyReply, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) AuthSignIn(ctx context.Context, in *AuthSignInRequest, opts ...grpc.CallOption) (*AuthSignInReply, error) {
	out := new(AuthSignInReply)
	err := c.cc.Invoke(ctx, Auth_AuthSignIn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) AuthSignUp(ctx context.Context, in *AuthSignUpRequest, opts ...grpc.CallOption) (*AuthSignUpReply, error) {
	out := new(AuthSignUpReply)
	err := c.cc.Invoke(ctx, Auth_AuthSignUp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) AuthVerify(ctx context.Context, in *AuthVerifyRequest, opts ...grpc.CallOption) (*AuthVerifyReply, error) {
	out := new(AuthVerifyReply)
	err := c.cc.Invoke(ctx, Auth_AuthVerify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility
type AuthServer interface {
	AuthSignIn(context.Context, *AuthSignInRequest) (*AuthSignInReply, error)
	AuthSignUp(context.Context, *AuthSignUpRequest) (*AuthSignUpReply, error)
	AuthVerify(context.Context, *AuthVerifyRequest) (*AuthVerifyReply, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (UnimplementedAuthServer) AuthSignIn(context.Context, *AuthSignInRequest) (*AuthSignInReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthSignIn not implemented")
}
func (UnimplementedAuthServer) AuthSignUp(context.Context, *AuthSignUpRequest) (*AuthSignUpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthSignUp not implemented")
}
func (UnimplementedAuthServer) AuthVerify(context.Context, *AuthVerifyRequest) (*AuthVerifyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthVerify not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_AuthSignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthSignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthSignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_AuthSignIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthSignIn(ctx, req.(*AuthSignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_AuthSignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthSignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthSignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_AuthSignUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthSignUp(ctx, req.(*AuthSignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_AuthVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_AuthVerify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthVerify(ctx, req.(*AuthVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.service.dex_member.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthSignIn",
			Handler:    _Auth_AuthSignIn_Handler,
		},
		{
			MethodName: "AuthSignUp",
			Handler:    _Auth_AuthSignUp_Handler,
		},
		{
			MethodName: "AuthVerify",
			Handler:    _Auth_AuthVerify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/dex-member/auth.proto",
}
